import * as z from "zod/v4";
import type { McpServer } from "@modelcontextprotocol/server";
import { db, uid } from "../../db";
import { getTimeline, placeAssetFramesBatch, placeFrame, reorderSteps, setStepDuration, syncAxis } from "../../timeline";
import { broadcast } from "../../ws";
import { err, ok } from "../helpers";
import { invalidateProjectUndo } from "../../undo";

const axis = (id:string)=>db.query("SELECT id,project_id FROM animation_axes WHERE id=?").get(id) as {id:string;project_id:string}|null;
const notify=(projectId:string,ids={})=>{invalidateProjectUndo(projectId);broadcast("timeline_changed",{projectId,...ids});};
const effectSchema=z.object({strokes:z.array(z.object({color:z.string().regex(/^#[0-9a-fA-F]{6}$/),size:z.number().min(1).max(256),brush:z.enum(["slash","bristle","dry","spark","echo"]).optional(),points:z.array(z.object({x:z.number(),y:z.number(),pressure:z.number().min(0.1).max(1)})).min(1).max(4096)})).max(128),offset_x:z.number(),offset_y:z.number(),scale:z.number().min(0.1).max(8),rotation:z.number().min(-Math.PI).max(Math.PI),opacity:z.number().min(0).max(1),style:z.enum(["flame","energy","ink"]).optional()});
export function register(server:McpServer) {
  server.registerTool("get_timeline",{title:"Get Timeline",description:"Get every animation axis and the selected/default axis tracks, shared steps, and composited frame cells.",inputSchema:z.object({projectId:z.string(),axisId:z.string().optional()}),annotations:{readOnlyHint:true}},async({projectId,axisId})=>{try{return ok(getTimeline(projectId,axisId));}catch(e){return err((e as Error).message)}});
  server.registerTool("create_track",{title:"Create Track",description:"Append a compositing track to an animation axis.",inputSchema:z.object({axisId:z.string(),name:z.string(),visible:z.number().int().min(0).max(1).optional(),locked:z.number().int().min(0).max(1).optional()})},async({axisId,name,visible,locked})=>{const a=axis(axisId);if(!a)return err("动画轴不存在");const id=uid(),idx=(db.query("SELECT COALESCE(MAX(idx),-1)+1 n FROM animation_tracks WHERE axis_id=?").get(axisId) as any).n;db.query("INSERT INTO animation_tracks VALUES (?,?,?,?,?,?,0)").run(id,axisId,name||"Track",idx,visible??1,locked??0);notify(a.project_id,{axisId,trackId:id});return ok({track:db.query("SELECT * FROM animation_tracks WHERE id=?").get(id)});});
  server.registerTool("update_track",{title:"Update Track",description:"Update a track name, visibility, or lock state.",inputSchema:z.object({trackId:z.string(),name:z.string().optional(),visible:z.number().int().min(0).max(1).optional(),locked:z.number().int().min(0).max(1).optional()})},async({trackId,...p})=>{const tr=db.query("SELECT t.*,a.project_id FROM animation_tracks t JOIN animation_axes a ON a.id=t.axis_id WHERE t.id=?").get(trackId) as any;if(!tr)return err("轨道不存在");const keys=Object.keys(p).filter(k=>(p as any)[k]!==undefined);if(!keys.length)return err("没有可更新字段");db.query(`UPDATE animation_tracks SET ${keys.map(k=>`${k}=?`).join(",")} WHERE id=?`).run(...keys.map(k=>(p as any)[k]),trackId);notify(tr.project_id,{axisId:tr.axis_id,trackId});return ok({track:db.query("SELECT * FROM animation_tracks WHERE id=?").get(trackId)});});
  server.registerTool("delete_track",{title:"Delete Track",description:"Delete a non-primary, non-sole track and its cells; empty steps are pruned.",inputSchema:z.object({trackId:z.string()})},async({trackId})=>{const tr=db.query("SELECT t.*,a.project_id FROM animation_tracks t JOIN animation_axes a ON a.id=t.axis_id WHERE t.id=?").get(trackId) as any;if(!tr)return err("轨道不存在");if(tr.is_primary||(db.query("SELECT COUNT(*) n FROM animation_tracks WHERE axis_id=?").get(tr.axis_id) as any).n<=1)return err("不能删除主轨或唯一轨道");db.transaction(()=>{db.query("DELETE FROM attack_effects WHERE track_id=?").run(trackId);db.query("DELETE FROM frames WHERE track_id=?").run(trackId);db.query("DELETE FROM animation_tracks WHERE id=?").run(trackId);db.query("DELETE FROM animation_steps WHERE axis_id=? AND NOT EXISTS(SELECT 1 FROM frames WHERE step_id=animation_steps.id) AND NOT EXISTS(SELECT 1 FROM attack_effects WHERE step_id=animation_steps.id)").run(tr.axis_id);})();syncAxis(tr.axis_id);notify(tr.project_id,{axisId:tr.axis_id,trackId});return ok({ok:true});});
  server.registerTool("reorder_tracks",{title:"Reorder Tracks",description:"Set the exact, unique order of all tracks on an axis.",inputSchema:z.object({axisId:z.string(),trackIds:z.array(z.string())})},async({axisId,trackIds})=>{const a=axis(axisId);if(!a)return err("动画轴不存在");const ids=(db.query("SELECT id FROM animation_tracks WHERE axis_id=?").all(axisId) as any[]).map(x=>x.id),set=new Set(ids);if(trackIds.length!==set.size||new Set(trackIds).size!==trackIds.length||!trackIds.every(x=>set.has(x)))return err("trackIds 必须恰好且不重复地包含全部轨道");db.transaction(()=>{trackIds.forEach((id,i)=>db.query("UPDATE animation_tracks SET idx=? WHERE id=?").run(-i-1,id));trackIds.forEach((id,i)=>db.query("UPDATE animation_tracks SET idx=? WHERE id=?").run(i,id));})();notify(a.project_id,{axisId});return ok({ok:true});});
  server.registerTool("create_step",{title:"Create Step",description:"Append a shared timeline step.",inputSchema:z.object({axisId:z.string(),duration:z.number().int().min(1).max(600).optional()})},async({axisId,duration})=>{const a=axis(axisId);if(!a)return err("动画轴不存在");const id=uid(),idx=(db.query("SELECT COALESCE(MAX(idx),-1)+1 n FROM animation_steps WHERE axis_id=?").get(axisId) as any).n;db.query("INSERT INTO animation_steps VALUES (?,?,?,?)").run(id,axisId,idx,duration??1);notify(a.project_id,{axisId,stepId:id});return ok({step:db.query("SELECT * FROM animation_steps WHERE id=?").get(id)});});
  server.registerTool("update_step",{title:"Update Step",description:"Update authoritative shared duration and all frame compatibility mirrors.",inputSchema:z.object({stepId:z.string(),duration:z.number().int().min(1).max(600)})},async({stepId,duration})=>{const s=db.query("SELECT s.*,a.project_id FROM animation_steps s JOIN animation_axes a ON a.id=s.axis_id WHERE s.id=?").get(stepId) as any;if(!s)return err("步骤不存在");setStepDuration(stepId,duration);notify(s.project_id,{axisId:s.axis_id,stepId});return ok({step:db.query("SELECT * FROM animation_steps WHERE id=?").get(stepId)});});
  server.registerTool("delete_step",{title:"Delete Step",description:"Delete a shared step and every frame/effect cell occupying it.",inputSchema:z.object({stepId:z.string()})},async({stepId})=>{const s=db.query("SELECT s.*,a.project_id FROM animation_steps s JOIN animation_axes a ON a.id=s.axis_id WHERE s.id=?").get(stepId) as any;if(!s)return err("步骤不存在");db.transaction(()=>{db.query("DELETE FROM attack_effects WHERE step_id=?").run(stepId);db.query("DELETE FROM frames WHERE step_id=?").run(stepId);db.query("DELETE FROM animation_steps WHERE id=?").run(stepId);})();syncAxis(s.axis_id);notify(s.project_id,{axisId:s.axis_id,stepId});return ok({ok:true});});
  server.registerTool("reorder_steps",{title:"Reorder Steps",description:"Set the exact, unique order of all shared steps on an axis.",inputSchema:z.object({axisId:z.string(),stepIds:z.array(z.string())})},async({axisId,stepIds})=>{const a=axis(axisId);if(!a)return err("动画轴不存在");try{reorderSteps(axisId,stepIds)}catch(e){return err((e as Error).message)}notify(a.project_id,{axisId});return ok({ok:true});});
  server.registerTool("move_frame_cell",{title:"Move Frame Cell",description:"Place a reusable frame asset or move a timeline cell. Set copy=true when assembling from an asset so the source remains in the asset panel; swap=true replaces an occupied target.",inputSchema:z.object({frameId:z.string(),trackId:z.string(),stepId:z.string(),swap:z.boolean().optional(),copy:z.boolean().optional()})},async({frameId,trackId,stepId,swap,copy})=>{try{const frame=placeFrame(frameId,trackId,stepId,swap??false,copy??false);notify(frame.project_id,{frameId:frame.id,trackId,stepId});return ok({frame});}catch(e){return err((e as Error).message==="OCCUPIED"?"目标坐标已占用":(e as Error).message)}});
  server.registerTool("place_frames_batch",{title:"Place Frames Batch",description:"Copy multiple reusable frame assets onto a track starting at a step (occupied cells on that track are evicted back to the asset pool; new steps are appended if the run overflows the existing columns). Order follows the supplied frameIds.",inputSchema:z.object({trackId:z.string(),frameIds:z.array(z.string()),startStepId:z.string().optional()})},async({trackId,frameIds,startStepId})=>{const tr=db.query("SELECT t.axis_id,a.project_id FROM animation_tracks t JOIN animation_axes a ON a.id=t.axis_id WHERE t.id=?").get(trackId) as {axis_id:string;project_id:string}|null;if(!tr)return err("轨道不存在");try{const ids=placeAssetFramesBatch(tr.project_id,frameIds,{axisId:tr.axis_id,trackId,startStepId});notify(tr.project_id,{axisId:tr.axis_id,trackId});return ok({frameIds:ids});}catch(e){return err((e as Error).message);}});
  server.registerTool("upsert_attack_effect",{title:"Upsert Attack Effect",description:"Create or replace an editable attack effect in any timeline track/step cell, including a cell with no image frame.",inputSchema:z.object({trackId:z.string(),stepId:z.string(),effect:effectSchema})},async({trackId,stepId,effect})=>{const c=db.query(`SELECT a.project_id FROM animation_tracks t JOIN animation_axes a ON a.id=t.axis_id JOIN animation_steps s ON s.id=? AND s.axis_id=t.axis_id WHERE t.id=?`).get(stepId,trackId) as {project_id:string}|null;if(!c)return err("轨道与步骤不属于同一动画轴");const old=db.query("SELECT id FROM attack_effects WHERE track_id=? AND step_id=?").get(trackId,stepId) as {id:string}|null;const id=old?.id??uid();if(old)db.query("UPDATE attack_effects SET effect=? WHERE id=?").run(JSON.stringify(effect),id);else db.query("INSERT INTO attack_effects VALUES (?,?,?,?,?,?)").run(id,c.project_id,trackId,stepId,JSON.stringify(effect),Date.now());notify(c.project_id,{trackId,stepId,effectId:id});return ok({effectId:id});});
}
