import { Elysia, t } from "elysia";
import { db, uid } from "../db";
import { clearFramePlacement, getTimeline, placeAssetFramesBatch, placeFrame, reorderSteps, setStepDuration, syncAxis } from "../timeline";
import { broadcast } from "../ws";

const changed = (projectId: string, extra: Record<string, unknown> = {}) => broadcast("timeline_changed", { projectId, ...extra });
const axisContext = (axisId: string) => db.query("SELECT id,project_id FROM animation_axes WHERE id=?").get(axisId) as {id:string;project_id:string}|null;
const trackContext = (id: string) => db.query("SELECT t.*,a.project_id FROM animation_tracks t JOIN animation_axes a ON a.id=t.axis_id WHERE t.id=?").get(id) as any;
const stepContext = (id: string) => db.query("SELECT s.*,a.project_id FROM animation_steps s JOIN animation_axes a ON a.id=s.axis_id WHERE s.id=?").get(id) as any;

export const timelineApi = new Elysia({ prefix: "/api" })
  .get("/projects/:id/timeline", ({params,query,status}) => { try { return getTimeline(params.id,query.axisId); } catch(e) { return status(404,(e as Error).message); } }, { query:t.Object({axisId:t.Optional(t.String())}) })
  .post("/projects/:id/axes", ({params,body,status}) => {
    if(!db.query("SELECT id FROM projects WHERE id=?").get(params.id)) return status(404,"项目不存在");
    const id=uid(), idx=(db.query("SELECT COALESCE(MAX(idx),-1)+1 next FROM animation_axes WHERE project_id=?").get(params.id) as any).next;
    db.transaction(()=>{ db.query("INSERT INTO animation_axes VALUES (?,?,?,?,?,?)").run(id,params.id,body.name.trim()||"Animation",idx,body.fps??8,Date.now()); const tid=uid(); db.query("INSERT INTO animation_tracks VALUES (?,?, 'Main',0,1,0,1)").run(tid,id); })(); changed(params.id,{axisId:id}); return {axis:db.query("SELECT * FROM animation_axes WHERE id=?").get(id)};
  },{body:t.Object({name:t.String(),fps:t.Optional(t.Integer({minimum:1,maximum:120}))})})
  .patch("/axes/:id", ({params,body,status})=>{ const a=axisContext(params.id); if(!a)return status(404,"动画轴不存在"); const sets:string[]=[],vals:any[]=[]; if(body.name!==undefined){sets.push("name=?");vals.push(body.name.trim()||"Animation");} if(body.fps!==undefined){sets.push("fps=?");vals.push(body.fps);} if(!sets.length)return status(400,"没有可更新字段"); db.query(`UPDATE animation_axes SET ${sets.join(",")} WHERE id=?`).run(...vals,params.id); changed(a.project_id,{axisId:params.id}); return {axis:db.query("SELECT * FROM animation_axes WHERE id=?").get(params.id)};},{body:t.Object({name:t.Optional(t.String()),fps:t.Optional(t.Integer({minimum:1,maximum:120}))})})
  .delete("/axes/:id",({params,status})=>{const a=axisContext(params.id);if(!a)return status(404,"动画轴不存在");const count=(db.query("SELECT COUNT(*) n FROM animation_axes WHERE project_id=?").get(a.project_id) as any).n;if(count<=1)return status(409,"不能删除项目唯一的动画轴");db.transaction(()=>{db.query("DELETE FROM attack_effects WHERE track_id IN (SELECT id FROM animation_tracks WHERE axis_id=?)").run(params.id);db.query("DELETE FROM frames WHERE track_id IN (SELECT id FROM animation_tracks WHERE axis_id=?)").run(params.id);db.query("DELETE FROM animation_steps WHERE axis_id=?").run(params.id);db.query("DELETE FROM animation_tracks WHERE axis_id=?").run(params.id);db.query("DELETE FROM animation_axes WHERE id=?").run(params.id);})();changed(a.project_id,{axisId:params.id});return {ok:true};})
  .post("/axes/:id/tracks",({params,body,status})=>{const a=axisContext(params.id);if(!a)return status(404,"动画轴不存在");const id=uid(),idx=(db.query("SELECT COALESCE(MAX(idx),-1)+1 next FROM animation_tracks WHERE axis_id=?").get(params.id) as any).next;db.query("INSERT INTO animation_tracks VALUES (?,?,?,?,?,?,0)").run(id,params.id,body.name.trim()||"Track",idx,body.visible??1,body.locked??0);changed(a.project_id,{axisId:params.id,trackId:id});return {track:db.query("SELECT * FROM animation_tracks WHERE id=?").get(id)};},{body:t.Object({name:t.String(),visible:t.Optional(t.Integer({minimum:0,maximum:1})),locked:t.Optional(t.Integer({minimum:0,maximum:1}))})})
  .patch("/tracks/:id",({params,body,status})=>{const tr=trackContext(params.id);if(!tr)return status(404,"轨道不存在");const keys=["name","visible","locked"] as const;const present=keys.filter(k=>body[k]!==undefined);if(!present.length)return status(400,"没有可更新字段");const values=present.map(k=>k==="name"?(body[k] as string).trim()||"Track":body[k]!) as Array<string|number>;db.query(`UPDATE animation_tracks SET ${present.map(k=>`${k}=?`).join(",")} WHERE id=?`).run(...values,params.id);changed(tr.project_id,{axisId:tr.axis_id,trackId:params.id});return {track:db.query("SELECT * FROM animation_tracks WHERE id=?").get(params.id)};},{body:t.Object({name:t.Optional(t.String()),visible:t.Optional(t.Integer({minimum:0,maximum:1})),locked:t.Optional(t.Integer({minimum:0,maximum:1}))})})
  .delete("/tracks/:id",({params,status})=>{const tr=trackContext(params.id);if(!tr)return status(404,"轨道不存在");const n=(db.query("SELECT COUNT(*) n FROM animation_tracks WHERE axis_id=?").get(tr.axis_id) as any).n;if(n<=1||tr.is_primary)return status(409,"不能删除唯一轨道或主轨");db.transaction(()=>{db.query("DELETE FROM attack_effects WHERE track_id=?").run(params.id);db.query("DELETE FROM frames WHERE track_id=?").run(params.id);db.query("DELETE FROM animation_tracks WHERE id=?").run(params.id);db.query("DELETE FROM animation_steps WHERE axis_id=? AND NOT EXISTS(SELECT 1 FROM frames WHERE step_id=animation_steps.id) AND NOT EXISTS(SELECT 1 FROM attack_effects WHERE step_id=animation_steps.id)").run(tr.axis_id);})();syncAxis(tr.axis_id);changed(tr.project_id,{axisId:tr.axis_id,trackId:params.id});return {ok:true};})
  .post("/axes/:id/tracks/reorder",({params,body,status})=>{const a=axisContext(params.id);if(!a)return status(404,"动画轴不存在");const rows=db.query("SELECT id FROM animation_tracks WHERE axis_id=?").all(params.id) as any[];const set=new Set(rows.map(x=>x.id));if(body.trackIds.length!==set.size||new Set(body.trackIds).size!==body.trackIds.length||!body.trackIds.every(x=>set.has(x)))return status(400,"trackIds 必须恰好且不重复地包含全部轨道");db.transaction(()=>{body.trackIds.forEach((id,i)=>db.query("UPDATE animation_tracks SET idx=? WHERE id=?").run(-i-1,id));body.trackIds.forEach((id,i)=>db.query("UPDATE animation_tracks SET idx=? WHERE id=?").run(i,id));})();changed(a.project_id,{axisId:params.id});return {ok:true};},{body:t.Object({trackIds:t.Array(t.String(),{minItems:1})})})
  .post("/axes/:id/steps",({params,body,status})=>{const a=axisContext(params.id);if(!a)return status(404,"动画轴不存在");const id=uid(),idx=(db.query("SELECT COALESCE(MAX(idx),-1)+1 next FROM animation_steps WHERE axis_id=?").get(params.id) as any).next;db.query("INSERT INTO animation_steps VALUES (?,?,?,?)").run(id,params.id,idx,body.duration??1);changed(a.project_id,{axisId:params.id,stepId:id});return {step:db.query("SELECT * FROM animation_steps WHERE id=?").get(id)};},{body:t.Object({duration:t.Optional(t.Integer({minimum:1,maximum:600}))})})
  .patch("/steps/:id",({params,body,status})=>{const s=stepContext(params.id);if(!s)return status(404,"步骤不存在");setStepDuration(params.id,body.duration);changed(s.project_id,{axisId:s.axis_id,stepId:params.id});return {step:db.query("SELECT * FROM animation_steps WHERE id=?").get(params.id)};},{body:t.Object({duration:t.Integer({minimum:1,maximum:600})})})
  .delete("/steps/:id",({params,status})=>{const s=stepContext(params.id);if(!s)return status(404,"步骤不存在");db.transaction(()=>{db.query("DELETE FROM attack_effects WHERE step_id=?").run(params.id);db.query("DELETE FROM frames WHERE step_id=?").run(params.id);db.query("DELETE FROM animation_steps WHERE id=?").run(params.id);})();syncAxis(s.axis_id);changed(s.project_id,{axisId:s.axis_id,stepId:params.id});return {ok:true};})
  .post("/axes/:id/steps/reorder",({params,body,status})=>{const a=axisContext(params.id);if(!a)return status(404,"动画轴不存在");try{reorderSteps(params.id,body.stepIds);}catch(e){return status(400,(e as Error).message)}changed(a.project_id,{axisId:params.id});return {ok:true};},{body:t.Object({stepIds:t.Array(t.String())})})
  .patch("/frames/:id/placement",({params,body,status})=>{try{const frame=placeFrame(params.id,body.trackId,body.stepId,body.swap??false,body.copy??false);changed(frame.project_id,{frameId:frame.id,trackId:body.trackId,stepId:body.stepId});return {frame};}catch(e){const m=(e as Error).message;return status(m==="OCCUPIED"?409:m==="帧不存在"?404:400,m==="OCCUPIED"?"目标轨道步骤已被占用":m);}},{body:t.Object({trackId:t.String(),stepId:t.String(),swap:t.Optional(t.Boolean()),copy:t.Optional(t.Boolean())})})
  .delete("/frames/:id/placement",({params,status})=>{const frame=clearFramePlacement(params.id);if(!frame)return status(404,"轨道单元格不存在");changed(frame.project_id,{frameId:frame.id,trackId:frame.track_id,stepId:frame.step_id});return {ok:true};})
  .post("/tracks/:id/place-frames",({params,body,status})=>{const tr=trackContext(params.id);if(!tr)return status(404,"轨道不存在");try{const frameIds=placeAssetFramesBatch(tr.project_id,body.frameIds,{axisId:tr.axis_id,trackId:params.id,startStepId:body.startStepId});changed(tr.project_id,{axisId:tr.axis_id,trackId:params.id});return {frameIds};}catch(e){return status(400,(e as Error).message);}},{body:t.Object({frameIds:t.Array(t.String(),{minItems:1}),startStepId:t.Optional(t.String())})});
